version: '3.8'
services:
  app:
    container_name: mocker
    image: mocker-0.0.1
    build: .
    env_file:
      - .env
    ports:
      - "8445:8445"
    depends_on:
      - postgres
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
      POSTGRES_DB: mocker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: